### ISSUE TITLE
Unable to get track info display in html files

### ISSUE THREAD

**Issue by jlad00** [erikrichardlarson/unbox#10]
I cant seem to get the http://localhost:8080/play_history.html or http://localhost:8080/now_playing.html to display any track information. The page loads with the "now playing" banner but just no info.  The app itself is displaying the current playing track and I see info in the text and json files getting updated. Anyone else run into this?  Since I stream from a separate computer, I'd like to bring up the browser on that PC to display the info in OBS, but obviously need to get working locally first. Thanks.

**Comment by wayfu** [comment]
the text is white on white

**Comment by jlad00** [comment]
Aha, appreciate the tip @wayfu . I had looked at the page source previously and noticed the "white" tags but neglected to look at the console errors. I also had a browser plugin blocking GET requests to the json files. solved. Thanks again.
