### ISSUE TITLE
Crash when playing with Rekordbox 6 in Mac silicon  

### ISSUE THREAD

**Issue by djfatmango** [erikrichardlarson/unbox#100]
I am a mac silicon M1 user, I can use Rekordbox 6 without problem while running OBS but when I open Unbox the mac crashes.

**Comment by erikrichardlarson** [comment]
I would try out the latest release here, I've updated the Mac app quite a bit so it shouldn't crash anymore: https://github.com/erikrichardlarson/unbox/releases/download/11/unbox-mac.zip

Just let me know if you run into any issues.

**Comment by djfatmango** [comment]
Yesterday I used it for about 4 hours and there was no problem, well done!
