### ISSUE TITLE
64 bit on macos

### ISSUE THREAD

**Issue by b0ll3** [erikrichardlarson/unbox#107]
will there be a 64 bit version for macosx?

**Comment by erikrichardlarson** [comment]
The current MacOS app should be a 64 bit application, are you seeing otherwise / running into issues?

**Comment by b0ll3** [comment]
yes, unfortunately it looks like this here :(

**Comment by erikrichardlarson** [comment]
Sorry not seeing a linked screenshot, feel free to post it here again and I can take a look

**Comment by b0ll3** [comment]
<img width="633" alt="CleanShot 2023-06-12 at 06 54 37" src="https://github.com/erikrichardlarson/unbox/assets/73824590/e22d89c4-644c-4899-8d42-e227eed203e2">
 ups, sorry
here it is hopefully

**Comment by erikrichardlarson** [comment]
Thanks, I think you're on an Intel Mac? I can get a build out that works on Intel if that's the case, just let me know

**Comment by b0ll3** [comment]
yes i am
and that would be awesome :)

**Comment by erikrichardlarson** [comment]
Nice will get that over to you today

**Comment by erikrichardlarson** [comment]
Here's a version that should work on your mac, just let me know if you run into any issues: https://github.com/erikrichardlarson/unbox/releases/download/11/unbox-mac-universal.zip

**Comment by b0ll3** [comment]
Yes! thanks a lot!!!
Will test it in the coming days

**Comment by b0ll3** [comment]
ok,
when i start the app i get the following error message:

A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot find module '/Applications/unbox.app/Contents/Resources/app-x64.asar/node_modules/@journeyapps/sqlcipher/lib/binding/napi-v6-darwin-x64/node_sqlite3.node'
Require stack:
- /Applications/unbox.app/Contents/Resources/app-x64.asar/node_modules/@journeyapps/sqlcipher/lib/sqlite3-binding.js
- /Applications/unbox.app/Contents/Resources/app-x64.asar/node_modules/@journeyapps/sqlcipher/lib/sqlite3.js
- /Applications/unbox.app/Contents/Resources/app-x64.asar/src/poller.js
- /Applications/unbox.app/Contents/Resources/app-x64.asar/src/index.js
- /Applications/unbox.app/Contents/Resources/app.asar/index.js
- 
at Module._resolveFilename (node:internal/modules/cjs/loader:1054:15)
at n._resolveFilename (node:electron/js2c/browser_init:2:109877)
at Module._load (node:internal/modules/cjs/loader:900:27)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1120:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object.<anonymous> (/Applications/unbox.app/Contents/Resources/app-x64.asar/node_modules/@journeyapps/sqlcipher/lib/sqlite3-binding.js:4:15)
at Module._compile (node:internal/modules/cjs/loader:1241:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1296:10)
at Module.load (node:internal/modules/cjs/loader:1096:32)

**Comment by erikrichardlarson** [comment]
Ah sorry about that, try this build instead: https://github.com/erikrichardlarson/unbox/releases/download/11/unbox-mac-x64.zip

**Comment by b0ll3** [comment]
thanks. this works - up to one point :/
I have copied and selected the D2 file in my traktor app.
but then when i start unbox and it says it can't connect to my traktor app
(see attached screenshots)
<img width="491" alt="CleanShot 2023-06-21 at 01 03 10" src="https://github.com/erikrichardlarson/unbox/assets/73824590/070ff111-07fa-4e7b-9b87-57c311d93c0d">
<img width="839" alt="CleanShot 2023-06-21 at 01 04 26" src="https://github.com/erikrichardlarson/unbox/assets/73824590/06f3c131-3d1b-434f-bfef-8f23ce1783d6">

**Comment by erikrichardlarson** [comment]
Gotcha, are you playing a track in Traktor? Traktor follows master in real-time so a track has to be playing for the initial connection to be made.

**Comment by b0ll3** [comment]
ah ok. i will try that.

**Comment by b0ll3** [comment]
awesome. now it works :) Thanks

**Comment by erikrichardlarson** [comment]
Great to hear, let me know if you run into any more issues.
