### ISSUE TITLE
This plugin does not seem compatible with this version of VirtualDJ :((

### ISSUE THREAD

**Issue by lord-dantes** [erikrichardlarson/unbox#111]
Which version should i use? tell me please)
I use Mac, VirtualDJ v2023-m b7651.

https://i.ibb.co/0DNXLKL/2023-09-23-08-58-32.png

**Comment by erikrichardlarson** [comment]
Hmm that's the version I'm on and it's working as expected, which Mac are you on, Intel or one with a M chip?

**Comment by lord-dantes** [comment]
@erikrichardlarson M =)

**Comment by erikrichardlarson** [comment]
Gotcha, and this is the version you downloaded right? https://github.com/erikrichardlarson/unbox/releases/download/11/UnboxPlugin.bundle.zip

**Comment by lord-dantes** [comment]
@erikrichardlarson yeah, I downloaded it again from your link, but have again mistake which I was talking about ;((

New screens:
1) before of alert version
2) virtualDj marked plugin

https://ibb.co/d4pLS8W
https://i.ibb.co/88bX2zL/2023-09-25-08-37-11.png

**Comment by erikrichardlarson** [comment]
Which folder is the plugin in?

**Comment by erikrichardlarson** [comment]
Also just to confirm is the file unzipped and placed in the PluginsMacArm directory?

**Comment by lord-dantes** [comment]
@erikrichardlarson SoundEffect, and yes full file look like Unbox.bundle and has folder PluginsMacArm. 
(PluginsMacArm/SoundEffect)

**Comment by erikrichardlarson** [comment]
Hmm not sure what's going on here, is there any update available for your VirtualDJ on your end? Also can you please send over a screenshot of your version?

**Comment by erikrichardlarson** [comment]
Also can you try this version, just zipped up the exact bundle that is working for me, just let me know if it doesn't work.
[UnboxPlugin.bundle.zip](https://github.com/erikrichardlarson/unbox/files/12751704/UnboxPlugin.bundle.zip)

**Comment by erikrichardlarson** [comment]
Oh can you run this on the bundle from the terminal, just need to replace the /path with the actual path to UnboxPlugin.bundle 

`xattr -d com.apple.quarantine /path/UnboxPlugin.bundle
`

**Comment by erikrichardlarson** [comment]
Just let me know if you have issues running the command above, I just tested it on my end after receiving the same error you had and it's working as expected now.

**Comment by lord-dantes** [comment]
@erikrichardlarson its working! Thanks you so much!
