### ISSUE TITLE
Unbox can't connect (macos)

### ISSUE THREAD

**Issue by b0ll3** [erikrichardlarson/unbox#113]
I don't know if it is because I updated my iMac to 12.7.1 or because I updated Traktor to 3.10.1 16 (which I both did in the past seven days) but since I updated both this week Unbox can't connect to Traktor anymore :(

**Comment by erikrichardlarson** [comment]
Hey yeah just tested the latest traktor and it looks like the D2.qml file is overwritten on upgrade, can you download the D2 file from the readme here (https://github.com/erikrichardlarson/unbox/releases/download/11/D2.zip) and overwrite the existing D2 file you have in the /Applications/Native Instruments/Traktor Pro 3/Traktor.app/Contents/Resources/qml/CSI directory?

**Comment by b0ll3** [comment]
hm, didn't change anything, sadly
I only copied the D2.qml file, was that right?
Or should I also copy the Api-Folder?

**Comment by erikrichardlarson** [comment]
Hmm the D2 file should be the only thing needed, but yeah trying copying in the Api folder as well. Is D2 set as an active controller in Traktor itself?

**Comment by b0ll3** [comment]
doesn't work with the api folder copied either
And no, D2 is not set as active as I doesn't have one, I'm using the Z1. D2 doesn't show up in the traktor preferences either (I remember it did in former versions and was always wondering why - was that because of unbox?)

**Comment by b0ll3** [comment]
I'm still on Intel not mac silicon, if that is of any importance ....

**Comment by erikrichardlarson** [comment]
Oh it should show up in the controller manager like below, do you see this / can you add it?
<img width="645" alt="Screenshot 2023-11-11 at 4 57 33 PM" src="https://github.com/erikrichardlarson/unbox/assets/17460309/d72916dc-bdb3-403c-8797-b93866e967c8">

**Comment by erikrichardlarson** [comment]
Dropdown came up after clicking "Add..." <img width="477" alt="Screenshot 2023-11-11 at 4 58 31 PM" src="https://github.com/erikrichardlarson/unbox/assets/17460309/812afdaa-73f6-4a49-96c0-960999bf4b61">

**Comment by b0ll3** [comment]
YES! That dit it. Thanks for the fast help :)

**Comment by erikrichardlarson** [comment]
Awesome glad it's working!
