### ISSUE TITLE
Unbox Rekordbox in export mode?

### ISSUE THREAD

**Issue by Sigvaladson** [erikrichardlarson/unbox#12]
Hi, 

Is it possible to run unbox with Rekordbox in export mode?
Then I'm open the software, I don't get any information from my Rekordbox, I use only PC with Windows.

**Comment by erikrichardlarson** [comment]
Not yet, but there is an update coming very soon that will allow you to use export mode on rb6 if you're on Windows 64 bit, are you running rb6 on Windows 64?

**Comment by Sigvaladson** [comment]
I'm ussing Rekordbox 5 and Windows 10, 64 bit

**Comment by erikrichardlarson** [comment]
Yep that will work when this goes live, should be out sometime this week. I'll post here when it's live.

**Comment by erikrichardlarson** [comment]
@Sigvaladson the latest version should now work with export mode
