### ISSUE TITLE
Incompatible Unbox Plugin in Virtual DJ (Mac OS message: damaged file)

### ISSUE THREAD

**Issue by sambarbarossa** [erikrichardlarson/unbox#127]
Hi,

the UnboxPlugin.bundle downloaded (dated may 21. 2023) is not working with Virtual DJ. When I selected it from the list a Mac OS message says Damaged files, move to the trash. And then virtual dj mark it as "Incompatible".
What can I do?

<img width="299" alt="image" src="https://github.com/erikrichardlarson/unbox/assets/142320425/7d4d80f7-df52-460b-9998-ff70baed4eeb">

<img width="425" alt="image" src="https://github.com/erikrichardlarson/unbox/assets/142320425/5a0f7892-0710-46d0-986c-966d025f0bd2">

<img width="230" alt="image" src="https://github.com/erikrichardlarson/unbox/assets/142320425/ed9faf4c-0766-4d3c-aa8e-5fa1398d98ce">

Thank you

**Comment by erikrichardlarson** [comment]
Were you able to get this working?

**Comment by sambarbarossa** [comment]
Yes thank you! I’ve found the terminal commandIl giorno 11 apr 2024, alle ore 03:09, erikrichardlarson ***@***.***> ha scritto:﻿
Were you able to get this working?
