### ISSUE TITLE
Rekordbox 7.0.1.0021 having trouble connecting

### ISSUE THREAD

**Issue by sebdooris** [erikrichardlarson/unbox#128]
Receiving "We're having trouble connecting. Please reach out to us for support." with Rekordbox 7.0.1.0021 
unbox 11.3

**Comment by erikrichardlarson** [comment]
Are you on Mac or Windows? Currently working for me on Mac, also was this working before for you?

**Comment by sebdooris** [comment]
On Windows 11 fresh install. Tried running as Administrator too but same error. Appreciate the help

**Comment by sebdooris** [comment]
Can mark this one as user issue. I'll explain this was a fresh install of RB/unbox and had not played any track longer then 60 seconds in performance mode. After I played a few tracks unbox was able to establish a connection.

**Comment by erikrichardlarson** [comment]
Got it will close, thanks for the update
