### ISSUE TITLE
No issue - Kudos

### ISSUE THREAD

**Issue by DJNixInTheMix** [erikrichardlarson/unbox#14]
So I've been using this for about a month now.  After a few very minor complaints on my part, @erikrichardlarson you knocked it out of the park with this.  No where else has anyone been able to get track ID from rekordbox.  It is working great.  Many DJ's are asking me how I did it and I just send them here.  Thank you so much.

**Comment by erikrichardlarson** [comment]
Great to hear! Thank you, really appreciate the support! 

If you're on Windows 64 you can expect an update soon that gives you updates in real-time that follow rekordbox's master deck.
