### ISSUE TITLE
Error with Rekordbox 5

### ISSUE THREAD

**Issue by grantpeck** [erikrichardlarson/unbox#15]
This only happens when on the Rekordbox radio button and ive entered my Kuvo live url to track.

Get this error 

Uncaught exception:
Error: ENOENT: no such file or directory, open
Then it points to rekordboxAgent\storage\options.json

Any ideas?

Is it required i go to rekordbox 6?

**Comment by grantpeck** [comment]
Sorry just seen https://github.com/erikrichardlarson/unbox/issues/9

It isnt clear though in your documentation that you require Ver6 to least be installed etc

**Comment by erikrichardlarson** [comment]
Yeah right now rb6 is required with KUVO, but I'm going to update this with the next release and there will be a mode that bypasses KUVO entirely for rb5, and provides you real-time updates. I'll update the docs now to make this more explicit.

**Comment by grantpeck** [comment]
Many thanks for the update. Look forward to the update as kept 5 due to the DVS monthly fee of 10 a month.

________________________________
