### ISSUE TITLE
[Feature request] Use KUVO user page instead of playlist, to automatically get latest playlist. 

### ISSUE THREAD

**Issue by lord-carlos** [erikrichardlarson/unbox#16]
Hi mate. Grate software.

Would be great if I could use the KUVO user URL
For example: https://kuvo.com/user/XXXXX/djmix or https://kuvo.com/user/XXXXX or maybe just XXXXX?
And from that unbox can find the latest playlist.

If unbox now remembers the value the user would not need to enter or adjust anything on startup. Setup once, use many times.

Also it seams unbox does not remember any setting. (Color, program etc.) Is that a bug or do you want me to create a separate feature request?

**Comment by erikrichardlarson** [comment]
Thanks! Oh good idea, yeah all I'd need is a user id and I could find the latest playlist, I'll update this in the next release. 

The color should be remembered now so there may be a bug, the next release will have a new config and your last used settings will definitely be remembered so you shouldn't run into this issue soon. And your KUVO user id will be in this config.
