### ISSUE TITLE
Javascript Error - Virtual DJ

### ISSUE THREAD

**Issue by JoshuaSandefur** [erikrichardlarson/unbox#18]
I have tried running Unbox with Virtual DJ and keep receiving this error:
![Capture](https://user-images.githubusercontent.com/80117435/110144561-17a62000-7d9e-11eb-80de-98364f580cfa.PNG)

I did double-check to make sure the tracklist.txt file was there so I'm not exactly sure what the issue may be.

**Comment by erikrichardlarson** [comment]
Ah looks like this was the mac code, not the windows code, my bad. Just updated the windows release so you should be good  to go now. You can redownload [here](https://github.com/erikrichardlarson/unbox/releases/download/7.0/unbox-windows.zip) and it should work.

**Comment by JoshuaSandefur** [comment]
Hey Erik,

Thank you for the update.  I'm unfortunately getting a new error now:
![Capture](https://user-images.githubusercontent.com/80117435/110156498-a6ba3480-7dac-11eb-9663-40592fc9c77b.PNG)

I double-checked again to make sure the file was in the right spot.  
![Capture2](https://user-images.githubusercontent.com/80117435/110156548-b8034100-7dac-11eb-882b-ef1060a69fe2.PNG)

I don't know much about code, but if there is troubleshooting I can do on my end, let me know.

Thanks!

**Comment by erikrichardlarson** [comment]
Hmm I’ll try to get an update out here soon that should fix this, looks like we’re close to getting it working, it’s just the base user directory that isn’t coming through as expected.
