### ISSUE TITLE
How to get text to be in 2 lines only

### ISSUE THREAD

**Issue by djmel88** [erikrichardlarson/unbox#19]
How to get text to be in 2 lines only but extended out.  There are some tracks that are long and it display in 3 or 4 lines and it smooshes it

**Comment by lord-carlos** [comment]
Could it be that you need to make your browser source a higher resolution?

**Comment by djmel88** [comment]
I tried that it didn't work.

**Comment by erikrichardlarson** [comment]
Usually this is caused by the width of the browser source in OBS being too small, you can set it to 1200px on the OBS browser source settings page and it should work. Let me know if that doesn’t work.
