### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by mamiralek** [erikrichardlarson/unbox#2]

**Comment by mamiralek** [comment]
![Capture](https://user-images.githubusercontent.com/77330477/104308511-842e3c80-551c-11eb-821a-c04c41c81bab.PNG)

**Comment by erikrichardlarson** [comment]
It looks like there might not be anything in your rekordbox history currently, are you able to see any tracks in your rekordbox history folder? My history folder is on the bottom left and contains a few playlists, yours may be there too if any exist.

**Comment by AdvanceRatio** [comment]
I've been able to recreate this.  Seems to happen if either the title or artist field is blank in Rekordbox.

**Comment by LiorBracha91** [comment]
same here.
if u miss things on the tags there is a java error.
is it fixable?
or maybe let us decide if we want it to read tags or filename on the softwere...

**Comment by mamiralek** [comment]
Yeah okay this is the case for me.
History only had music videos (downloaded from YT) hence lack of tags.

**Comment by erikrichardlarson** [comment]
@AdvanceRatio @LiorBracha91 Yeah if the Artist or Track fields are empty this will break currently, I'll update the code to handle null values for either of these and just cast them as empty strings. 

@LiorBracha91 What other fields do you use in place of Artist and Track? I think viewers mostly want to see the Artist and Track fields so I'm trying to make sure those come over.

**Comment by LiorBracha91** [comment]
@erikrichardlarson 
on rekordbox i see it as "file name" on the list.
and the file name got everything 
bla - bla bla bla (bla edit) 128 bpm 2A

if u got a good automated tag fixer i would love that, but i didnt found one.

**Comment by erikrichardlarson** [comment]
Gotcha I could make it so filename is used if both Artist and Rrack are empty, how does that sound?

**Comment by LiorBracha91** [comment]
thats good but give us options if we want file name - or from tags artist and song name.
or u say that even if one of them is empty the softwere will take the file name?

**Comment by erikrichardlarson** [comment]
I was thinking if both were empty I could parse the filename and display that? I think you want to have the fallback behavior like this in case some of your tracks do have Artist or Title filled out.

**Comment by LiorBracha91** [comment]
they are never both empty here...
alot of artist names are missing but not the song title.

**Comment by erikrichardlarson** [comment]
Gotcha, I'll create a small app to help cleanup your library since it seems like the problem to solve here is getting the Artist and Track fields filled out as they should be. I'll send it your way when I have it built out.
