### ISSUE TITLE
Virtual DJ not working

### ISSUE THREAD

**Issue by stevexcite** [erikrichardlarson/unbox#21]
1st of all great program been using it with rekordbox fine on windows & mac but can't seem to get it working with virtual DJ just nothing is happening

**Comment by erikrichardlarson** [comment]
Thanks! Are you on windows with virtualdj mode running?

**Comment by stevexcite** [comment]
Yes on windows the go live button is still grey when using virtual DJ but is green when on rekordbox trying restart the app & virtual dj still no luck. Not trying on mac with virtual dj yet

**Comment by erikrichardlarson** [comment]
Gotcha yeah still having some issues on windows with accessing the documents directory, going to get an update out soon that should fix things. The Mac version should work now though if you want to test that out. I’ll be sure to post here when I have the windows update live.

**Comment by stevexcite** [comment]
ok will test the mac version & let you know if it works ok with virtual DJ :)

**Comment by stevexcite** [comment]
Tested today on mac the same issue with virtual DJ nothing happening. works fine with rekordbox. virtual DJ seem to be the same on mac & windows

**Comment by erikrichardlarson** [comment]
Gotcha can you send me your VirtualDJ history file? Just want to make sure the parser is working as expected and go from there.

**Comment by mrmacau** [comment]
Just came across this project.  Looks great.  Any news on this?  Tried it out on Windows 10 using VDJ and like above nothing seems to happen.

**Comment by mrmacau** [comment]
Never mind.  Unzipped to C:\ and it works perfectly.

**Comment by mrmacau** [comment]
> Never mind. Unzipped to C:\ and it works perfectly.

Scratch that.

I got this to work once and now every time I re open unbox, select Virtual DJ, select the overlay then on the last step the go live is grey.

**Comment by erikrichardlarson** [comment]
Interesting, the next version will take in the path of the virtual dj history folder directly which could help. But this could also be a parsing error, can you send me your history folder zipped so I can test the current code on it?

**Comment by mrmacau** [comment]
> Interesting, the next version will take in the path of the virtual dj history folder directly which could help. But this could also be a parsing error, can you send me your history folder zipped so I can test the current code on it?

Yeah.. it works then.  Then I close unbox and same as above.  Open unbox follow the prompts and nothing works.

History zip here. https://www.dropbox.com/s/zt54of96gt34zts/History.zip?dl=0

**Comment by stevexcite** [comment]
Any update on this working with Virtual DJ yet??

**Comment by erikrichardlarson** [comment]
Yeah I haven't had a chance to work on this much, I'll post here when I have a chance to look at the zipped file here and test the code some more.

**Comment by stevexcite** [comment]
ok thank you @erikrichardlarson appreciate everything you are doing & I look forward to testing this out for you..

**Comment by erikrichardlarson** [comment]
@stevexcite Hey I'm testing out the VirtualDJ mode now, could you please upload your history file again, want to make sure we can parse your history. Thanks!

**Comment by stevexcite** [comment]
[tracklist.txt](https://github.com/erikrichardlarson/unbox/files/6632958/tracklist.txt) is this what you are after??
