### ISSUE TITLE
Now playing in Denon Mode

### ISSUE THREAD

**Issue by emtex** [erikrichardlarson/unbox#23]
Hi,
so i just downloaded unbox for windows started my denon prime 4 in standalone mode and then i started unbox and configured it how i like it. selected asot. inserted the local host url and added it to my obs overlay. but all i see is the now playing text and nothing else.
did i something wrong?

**Comment by Wilxx** [comment]
I'm seeing the same of the Prime 4. I'll see what I can find by trying every option.

**Comment by emtex** [comment]
in the description it say denon prime 4 has to be online before switching on unbox? what does this mean? in standalone mode with internetconnection (wich makes the most sense) or connected to a pc (on wich you can use the prime 4 only as a controller). ( i am connected to my local network with my p4) since you play not on the same pc (because it is a standalone dj system you have to choose the url with the ip in front not local host. but no matter what i do i can't get any track info out of the p4. it doen't even show in play history in unbox main

**Comment by Wilxx** [comment]
Interesting.

I've given it a go under many conditions and I'm still not managing to get it working. There is someone here https://denondjforum.com/t/stagelinq-protocol-api/27578/66 that has managed to get it running under Terminal.

You may have to scroll a little but the post is there.

**Comment by Wilxx** [comment]
> what i also got from the description is the sentence: windows only supports, rekordbox, serato, virtual dj? is this still true or is the denon missing since the support from unbox for denon was added lately?

I think the support text hasn't been updated fully yet. Hopefully it will change once all issues are resolved.

**Comment by erikrichardlarson** [comment]
@emtex yeah it just means your player needs to be turned on and connected to the internet. there is support for windows, it seems that people are having issues with their Prime 4s and this right now so I'm creating a debug script that I'm going to send out soon so we can see where things are failing. 

Once we get things working fully I'll update the readme so it's not as confusing, thanks for the support!

**Comment by Wilxx** [comment]
Fantastic. I kinda thought that the Prime 4 was the issue as it seemed a little common. 

When crimsonsimon grabbed icedream's Prime 4 code I'm guessing the Prime 4 references could have been changed for SC5000/SC6000s?

https://denondjforum.com/t/stagelinq-protocol-api/27578/26

Just a hunch. Hopefully we'll get to run the debug and get a clearer picture of it. Thanks for the help so far and I'll be sure to drop you a tip.

**Comment by emtex** [comment]
> @emtex yeah it just means your player needs to be turned on and connected to the internet. there is support for windows, it seems that people are having issues with their Prime 4s and this right now so I'm creating a debug script that I'm going to send out soon so we can see where things are failing.
> 
> Once we get things working fully I'll update the readme so it's not as confusing, thanks for the support!

ah then i got it all right.
sounds good. let's hope you guys can get this to work. thanks for all the effort!

**Comment by erikrichardlarson** [comment]
@emtex @Wilxx yeah that's what I was thinking too, but I don't see any differences between the two really. the debug scripts are here btw: https://denondjforum.com/t/stagelinq-protocol-api/27578/81

**Comment by erikrichardlarson** [comment]
@emtex @Wilxx the latest release has updated denon executables that should be more stable, feel free to give them a try and report back!

**Comment by KenzoElectronicMusic** [comment]
I have this problem 

Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/kk/w4gc06_j3zn6rh4ypg5qlzq00000gn/T/AppTranslocation/A51C7A42-FB42-4364-B4DA-E443AD2CA61E/d/unbox.app/Contents/Resources/app/src/config.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at IpcMainImpl.<anonymous> (/private/var/folders/kk/w4gc06_j3zn6rh4ypg5qlzq00000gn/T/AppTranslocation/A51C7A42-FB42-4364-B4DA-E443AD2CA61E/d/unbox.app/Contents/Resources/app/src/index.js:271:10)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
    at WebContents.emit (events.js:223:5)

**Comment by erikrichardlarson** [comment]
On Mac you just need to move the application to your Documents or Applications folder, this error is caused by keeping the application in your Downloads folder. Lmk if that doesn't fix things!

**Comment by KenzoElectronicMusic** [comment]
Thank You with Terminal the application is running ok too but not connect with the Denon Players 

Enviado desde mi iPhone
