### ISSUE TITLE
Rekordbox 6.5.1 it close after launch "real time" options (WIN10)

### ISSUE THREAD

**Issue by dannysateler** [erikrichardlarson/unbox#28]
Hi all.

It's my first time with the program, i'm been looking for this solution for a long time and i would likme to use the real time option with Rekordbox.
But when I press "Launch" on the "Rekordbox Song Exporter" module, even when the Rekordbox aparently open propertly, it close few seconds after. I can't do anything.

Please tell me what you need from me to help to solve this "issue". I'm useing Rekordbox 6.5.1

![image](https://user-images.githubusercontent.com/80652493/111087441-72f3b300-8500-11eb-87f9-3055e9a42086.png)

Thanks in advance.
Danny

**Comment by erikrichardlarson** [comment]
Yeah at the moment this mode only works with 6.5.0, can you revert back to 6.5.0?

**Comment by dannysateler** [comment]
Thanks @erikrichardlarson . I tried the downgrade process, but i can't found the old version. Can you help me to find it?

**Comment by erikrichardlarson** [comment]
Wasn’t able to find it myself, but we have support for 6.5.1 now thanks to @Unreal-Dan so I’ll package the release early this week with unbox.

**Comment by chevy5727** [comment]
> Wasn’t able to find it myself, but we have support for 6.5.1 now thanks to @Unreal-Dan so I’ll package the release early this week with unbox.

ohoo great !!!

**Comment by Nass86** [comment]
@erikrichardlarson I'm new to Github and how this all works - I downloaded Unbox today. I couldn't tell if there was a later version so just reinstalled it. Did this Unreal Dan support get included in what I downloaded?

I have noticed when testing that Rekordbox is giving the current track a little over 1 minute into the next track (which makes sense for most DJs) so it would appear my Rekordbox 6.5.1 is working as of today without Kuvo (which is still broken on the Kuvo side)

**Comment by erikrichardlarson** [comment]
@Nass86 I haven't updated the code yet to include 6.5.1 support, it's coming soon though, currently working to get Denon support figured out, but this update is next on my list. Hmmm KUVO should be working in 6.5.1? If there are problems with the ordering or rendering, those are taken care of by Unbox since the data is scraped directly from KUVO and reordered properly.

**Comment by Nass86** [comment]
Kuvo doesn’t work. It’s likely not your fault. There’s an issue with it in general.

**Comment by dannysateler** [comment]
> Wasn’t able to find it myself, but we have support for 6.5.1 now thanks to @Unreal-Dan so I’ll package the release early this week with unbox.

Thanks in advance @erikrichardlarson  i thought you did it, downloaded the program, but i didn't realize that is a 7 days ago version. I can't wait for the new. (i activated the notifications for release)

**Comment by erikrichardlarson** [comment]
Ah yeah sorry meant to get to this but ran into some issues with Denon that I’m still trying to sort out. 6.5.1 support is coming soon though for sure. L

**Comment by Nass86** [comment]
I'm really confused. What doesn't work on 6.5.1? I'm on Mac and it's working. Do you mean Windows? Or will mine crash or something? I'm doing a 2 hour performance this sunday.

**Comment by erikrichardlarson** [comment]
Oh yeah sorry meant on Windows it doesn't work in real-time with 6.5.1, the non-real-time modes will work on Mac and Windows with 6.5.1.
