### ISSUE TITLE
Traktor pro 3 DVS problem

### ISSUE THREAD

**Issue by youmax01** [erikrichardlarson/unbox#29]
Hi, exellent work!
Traktor pro 3 only works with play/cue option, do not work with DVS playing.

**Comment by erikrichardlarson** [comment]
Thanks! Gotcha, when you're playing with your DVS setup, do the tracks show up in Traktor Pro 3?

**Comment by youmax01** [comment]
Hi!, yes Trktor show id3 in deks, but in output web page only show : NOW PLAYING.
in the same deck with the same theme when press PLAY in controller or screen (no DVS playing) show the names ok

**Comment by erikrichardlarson** [comment]
Can you send a screenshot of what Traktor looks like when the DVS is playing and no track is reported out? Just want to see how the track is displayed on the Traktor side. Thanks!

**Comment by youmax01** [comment]
Yes send to you. Do you have a mail for send it

**Comment by erikrichardlarson** [comment]
Yeah here you go: erikrichardlarson@gmail.com
