### ISSUE TITLE
Rekordbox display idea (OBS)

### ISSUE THREAD

**Issue by davecold** [erikrichardlarson/unbox#30]
Hey,

first let me say **AWESOME** work! i searched for a tool like that over 2 years (without to have a 2nd PC).

But i have a problem with the display info in OBS...i loop my tracks and like it to let them run from the drop (for beatmatching etc) before i mix the track. And here is the problem...your program shows the track info already before it mixed in (when it runs to long). 
Is there a alternative to handle that? 
Maybe something like the new Track must reach a special level of loudness (fader moving) or when you hit the Button from the deck (stop playing)?

Best Regards
Dave

**Comment by erikrichardlarson** [comment]
Thanks! So the Rekordbox Real-time and KUVO modes should follow the master deck and align with the faders / when your listeners actually hear the track played out, are you on Windows or Mac?

**Comment by davecold** [comment]
Im on Mac.
And yes it does...what i mean is: when i loop the new track for lets say 60sec or more it shows already the new track. But the old track is still running and have maybe 3min left to play.
I will check it again maybe i saw it wrong but im sure its doiing that.

**Comment by erikrichardlarson** [comment]
Gotcha, sounds like you're using the database mode which has this limitation right now. Have you tried the KUVO mode?

**Comment by davecold** [comment]
im on RB 6.5.1 in export mode so yeah.
And Kuvo no.

So there is no solution right now? :(

**Comment by erikrichardlarson** [comment]
Well KUVO should work for you, it's fairly easy to setup, at least I've tried to make it easy haha maybe give that a try?

**Comment by erikrichardlarson** [comment]
Would like to get a real-time launcher on Mac, but it's proven to be much trickier to inject code into Rekordbox on Mac than on Windows.
