### ISSUE TITLE
Mac - Is Unbox supposed to take up 1.4GB in space? (Puppeteer folder)

### ISSUE THREAD

**Issue by Nass86** [erikrichardlarson/unbox#31]
Seems heavy for the app. Somehow that folder is 931mb on its own.

When I drill further it is in

- Chromium Framework.framework
and then both
- Chromium Framework (201mb)
- Versions (617mb)

If its necessary to make it work then that's fine - it just seems heavy storage for the app.

**Comment by erikrichardlarson** [comment]
Yeah I definitely want to optimize the app size, this is on the todo list of things to update, I just need to find an alternative way to scrape KUVO which I think can be done. I'll post here when I have an update for this.
