### ISSUE TITLE
Small overlay in OBS

### ISSUE THREAD

**Issue by Paulluna78** [erikrichardlarson/unbox#34]
Hello, first of all, thank you very much for the information ... I want to tell you the following, I have mac and rekorbox, I did the whole procedure for Kuvo and when I go to add the URL of unbox in OBS the overlay appears so small that you see a very thin line, it is as if it were on a very small scale, I did tests with other urls and the result is normal ... I wanted to check the url of unbox, for example http: // localhost: 8080 / asot.html opening it in chrome and it looks good, and it is updated as the songs are played ... I don't know the problem, thanks for attending, greetings

**Comment by lord-carlos** [comment]
What resolution did you set in browser source in OBS?

**Comment by erikrichardlarson** [comment]
Hmmm yeah usually this is caused by not setting the resolution in OBS to the average browser size: 1366 x 784 

Can you try that resolution and let us know what it looks like?

**Comment by Nass86** [comment]
> Hello, first of all, thank you very much for the information ... I want to tell you the following, I have mac and rekorbox, I did the whole procedure for Kuvo and when I go to add the URL of unbox in OBS the overlay appears so small that you see a very thin line, it is as if it were on a very small scale, I did tests with other urls and the result is normal ... I wanted to check the url of unbox, for example http: // localhost: 8080 / asot.html opening it in chrome and it looks good, and it is updated as the songs are played ... I don't know the problem, thanks for attending, greetings

Hey out of interest, is kuvo working for you on a whole set (on Mac)? I'm on 6.5.1 and it really isn't working at all or does for a couple of tracks and stops. Kuvo's problem, not this app, as the site doesn't update from Rekordbox itself. Yours is working?

**Comment by Nass86** [comment]
> > Hey out of interest, is kuvo working for you on a whole set (on Mac)? I'm on 6.5.1 and it really isn't working at all or does for a couple of tracks and stops. Kuvo's problem, not this app, as the site doesn't update from Rekordbox itself. Yours is working?
> 
> Not the one you asked, but for me kuvo is working :)

Thanks - if you are on a Mac can you explain exactly what you do, and what version of Rekordbox you are on?

**Comment by Paulluna78** [comment]
> What resolution did you set in browser source in OBS?

1280X720 and so it looks: 
![Captura de pantalla 2021-03-30 a las 16 36 51](https://user-images.githubusercontent.com/81168817/113007406-7c268600-9176-11eb-976e-496dee7e8ade.png)

**Comment by Paulluna78** [comment]
> Hmmm yeah usually this is caused by not setting the resolution in OBS to the average browser size: 1366 x 784
> 
> Can you try that resolution and let us know what it looks like?

I tried it and it appears the same
![Captura de pantalla 2021-03-30 a las 16 36 51](https://user-images.githubusercontent.com/81168817/113007624-a9733400-9176-11eb-8da7-ea05dbebb400.png)

**Comment by Paulluna78** [comment]
> Hey out of interest, is kuvo working for you on a whole set (on Mac)? I'm on 6.5.1 and it really isn't working at all or does for a couple of tracks and stops. Kuvo's problem, not this app, as the site doesn't update from Rekordbox itself. Yours is working?

I have an old OBS because I have the El Capitan operating system on my mac and I use rekorbox 5. The problem I have is the size of the overlay, but the information of the track that is updating with kuvo works for me, because I tried the other file that of rekorbox_stream. txt.

**Comment by Paulluna78** [comment]
It already works for me but in the following way. I left the rekorbox on my mac and on another mac I left it to transmit, I updated to BIG SUR, and installed the latest version of OBS, and so if it worked for me.
