### ISSUE TITLE
Rekordbox real time

### ISSUE THREAD

**Issue by Johnf2021** [erikrichardlarson/unbox#35]
You got back to me on Reddit when I asked about this but I'm still having an issue.

I'm on Windows and when I run the real time option I get the box pop up that has the launch button. Initially it didn't do anything but I then noticed the path to the .exe by default looks for version 6.0 but I have Rekordbox 6.5. so I changed this to 6.5 so it matches my .exe file. If Rekordbox is open hitting launch doesn't do anything at all. If Rekordbox is closed and I hit launch, Rekordbox opens but as soon as it's loaded up it shuts itself again.

Is this because this is only compatible specifically with 6.0? 

I'm not sure the launch button is actually doing anything when I click it, should it change to something other than 'launch'?

**Comment by erikrichardlarson** [comment]
It sounds like you might have 6.5.1? Can you check your version number in rekordbox and lmk what it is

**Comment by Johnf2021** [comment]
Sorry you're right, it's 6.5.1

**Comment by erikrichardlarson** [comment]
Gotcha yeah I’ll have the version compatible with 6.5.1 out soon, I’ll post here when it’s live.

**Comment by Johnf2021** [comment]
Thanks a lot.

**Comment by benrhine** [comment]
I second can we get an option for closer to real time for the mac version as almost 90 seconds is very slow when using the rb option

**Comment by erikrichardlarson** [comment]
@benrhine Try out the KUVO mode on Mac, it will follow the master deck in near real-time.

**Comment by Johnf2021** [comment]
In terms of the 'real time' option, is there a plan to add this to mac too? To be honest for PC, that is when I'm mixing so by the time Ive missed a track in it then displays so it kind of works however I use mac for my radio show so I can be half way through a track before it updates.

**Comment by erikrichardlarson** [comment]
@Johnf2021 I'd like to add this option, but code injection on Mac is tricky, I'd use the KUVO mode which follows master if you're on Mac.

**Comment by Johnf2021** [comment]
Ok, thats understandable. My issue with Kuvo is it runs for around 30 mins then just stops working. I have tried multiple times and even sent them a support ticket but never received a response. 

So by using unbox with Kuvo how does this work differently to just using Kuvo on its own? I ask as perhaps this may bypass the Kuvo issue I always have.

**Comment by erikrichardlarson** [comment]
Oh weird, we scrape the KUVO website so if the write to the KUVO website doesn't happen then Unbox would freeze as well, but I'd try it out and see if it fails again.

**Comment by Johnf2021** [comment]
> Oh weird, we scrape the KUVO website so if the write to the KUVO website doesn't happen then Unbox would freeze as well, but I'd try it out and see if it fails again.

I'm trying it out now, 20 minutes so far so lets see what happens. The last thing is Im struggling to style the displayed text. I chose the ASPT option and any changes I make to the asot.html file don't make any difference. Am I looking in the right place?

**Comment by erikrichardlarson** [comment]
You're close, to style the text it's best to use CSS in OBS, the html file can't be edited directly at the moment since any changes will be overwritten by the app. Let me know if you run into any issues here.

**Comment by Johnf2021** [comment]
> You're close, to style the text it's best to use CSS in OBS, the html file can't be edited directly at the moment since any changes will be overwritten by the app. Let me know if you run into any issues here.

Ah, I didnt think of that. I'll do that then!

**Comment by Johnf2021** [comment]
And after about 45 minutes with Kuvo, its stopped :( Nothing has crashed, it just stops updating the kuvo playlist therefore unbox doesn't log any more tracks. At this point the kuvo button in rekordbox has just turned itself off. I'm sure there is some setting with a time limit as it does it each and every time I try it out, does anyone else reading this have the same issue?

**Comment by Johnf2021** [comment]
> You're close, to style the text it's best to use CSS in OBS, the html file can't be edited directly at the moment since any changes will be overwritten by the app. Let me know if you run into any issues here.

I've opted to just pick up artist.txt and track.txt as 2 seperate sources as I want them centred so seemed like the best option. All good with styling but one thing I cannot get to work is setting the font. I want to use Lato which is installed on the OBS machine and I can use it for a standard text source but the standard 'font-family: 'Lato', sans-serif;' doesn't work, nor does just font-family: 'Lato'; Same for Arial, no luck.

**Comment by Johnf2021** [comment]
> > Oh weird, we scrape the KUVO website so if the write to the KUVO website doesn't happen then Unbox would freeze as well, but I'd try it out and see if it fails again.
> 
> I'm trying it out now, 20 minutes so far so lets see what happens. The last thing is Im struggling to style the displayed text. I chose the ASPT option and any changes I make to the asot.html file don't make any difference. Am I looking in the right place?

Sorry, you know when that many things go wrong you just feel like not bothering? I have started another live playlist with kuvo and see how long it lasts this time but now the artist.txt and track.txt don't update unless I go in and refresh the cache manually even though I can see the actual artist.txt and track.txt files have in fact updated.

**Comment by Johnf2021** [comment]
> > > Oh weird, we scrape the KUVO website so if the write to the KUVO website doesn't happen then Unbox would freeze as well, but I'd try it out and see if it fails again.
> > 
> > 
> > I'm trying it out now, 20 minutes so far so lets see what happens. The last thing is Im struggling to style the displayed text. I chose the ASPT option and any changes I make to the asot.html file don't make any difference. Am I looking in the right place?
> 
> Sorry, you know when that many things go wrong you just feel like not bothering? I have started another live playlist with kuvo and see how long it lasts this time but now the artist.txt and track.txt don't update unless I go in and refresh the cache manually even though I can see the actual artist.txt and track.txt files have in fact updated.

Never mind, this kuvo session now cut off after 15 minutes! Again, the kuvo button has just turned itself off.

**Comment by HankeyThePoo** [comment]
So what happened to this feature? It's been removed from the latest release.

**Comment by erikrichardlarson** [comment]
@HankeyThePoo Ah sorry missed some of the code in the update, I'll have the real-time mode back in the latest release soon.

**Comment by erikrichardlarson** [comment]
@HankeyThePoo RB real-time is back in this release, thanks for pointing this out!

**Comment by djrexy** [comment]
> 
> 
> @HankeyThePoo RB real-time is back in this release, thanks for pointing this out!

still RB real-time for 6.5.0 only :(

**Comment by erikrichardlarson** [comment]
@djrexy Coming soon! Haven't had much time for this project but will soon.

**Comment by djrexy** [comment]
thank u!

**Comment by djrexy** [comment]
> 
> 
> @djrexy Coming soon! Haven't had much time for this project but will soon.

hello boss! do you forget ;)

**Comment by erikrichardlarson** [comment]
Haha nope it's coming soon, I'm working on the project full-time for the next week or so, there will be a lot of updates soon including this one.

**Comment by djrexy** [comment]
> 
> 
> there will be a lot of updates soon including this one.
OMFG !!! Good News Bro! I cant wait because KUVO after couple hours stop working and i have to restart KUVO once again to work. The best way is Recordbox real time but i have new version of RB 6.5.1and unbox real time not working. Anyway, i cant wait and BIIIIIIIIIIIIIG Thank U for your job!!!!

**Comment by HankeyThePoo** [comment]
Sorry for posting here, since it isn't an issue, but I'm wondering if it's possible to display cover artwork next to the titles or have you considered adding this down the line? Thanks for your work!

**Comment by erikrichardlarson** [comment]
No worries, yeah this will be actually be available in the next release, a few others have requested this as well.

**Comment by Johnf2021** [comment]
Cover art will be great. Kuvo grabs it from various databases but it's hot and miss unless you play 100% dance music. Using my own art would be awesome 👍

**Comment by HankeyThePoo** [comment]
Yeah, would be great if it'd pull the information from the mp3 or something, cause Kuvo hardly ever works when it comes to covers.

**Comment by djrexy** [comment]
we cant wait Boss! :)

**Comment by erikrichardlarson** [comment]
@djrexy The latest version is compatible with rekordbox 6.5.1 now, a lot more updates are coming, just waiting for Twitch to approve the new Panel Extension for Unbox. You can download it [here](https://github.com/erikrichardlarson/unbox/releases/download/8.3/unbox-windows.zip).

**Comment by djrexy** [comment]
this version for 6.5.1 working until i start using "loop" in track, after release of loop - unbox stop reading tracks. You seen this on my twitch stream.

**Comment by djrexy** [comment]
Version 6.5.2 is OUT.

**Comment by erikrichardlarson** [comment]
Yeah will be updating to include 6.5.2 today, should have it released by EOD. 

Also I wasn’t able to recreate the loop bug you mentioned, I did notice the master deck indicator wouldn’t switch sometimes when I switched away from a looping deck. Do your decks still switch the “Master” text to orange?

**Comment by djrexy** [comment]
yes, i think

niedz., 27 cze 2021 o 16:28 erikrichardlarson ***@***.***>
napisał(a):

**Comment by erikrichardlarson** [comment]
@djrexy 6.5.2 is now supported in the latest release, you can download it here, this may fix the issues you're having with looping: https://github.com/erikrichardlarson/unbox/releases/download/8.4/unbox-windows.zip

**Comment by djrexy** [comment]
Ass you seen yesterday on my stream-unbox stop working and message from
rekordbox has been visible"unexpected error"
picture below.
If you want i can send you my configured unbox but i dont think so will be
helpful. Just let me know. I will help u how i can.
[image: Przechwytywanie.PNG]

**Comment by erikrichardlarson** [comment]
@djrexy Sounds like the windows launcher is still buggy, is KUVO still giving you issues too?

**Comment by djrexy** [comment]
I think kuvo after couple hours stop working too.

niedz., 11 lip 2021, 18:28 użytkownik erikrichardlarson <
***@***.***> napisał:

**Comment by djrexy** [comment]
Rekordbox 6.6.1 is out. Could you update please? Or maybe make universal file exe for any rekordbox (for future)
Thanks!!

**Comment by erikrichardlarson** [comment]
@djrexy Yeah will have an update out for this soon!

**Comment by erikrichardlarson** [comment]
@djrexy The latest release has support for 6.6.1: https://github.com/erikrichardlarson/unbox/releases/download/10.0/unbox_windows.zip

**Comment by djrexy** [comment]
wow! so quick Bro, many thanks for good job Boss

**Comment by djrexy** [comment]
Rekordbox 6.6.1 is out Bro. please update. Many thanks Bro!

**Comment by erikrichardlarson** [comment]
Oh yeah I can update this, did the latest Rekordbox update break things for you?

**Comment by djrexy** [comment]
i dont wanna try update to 6.6.2 before unbox be ready :)

**Comment by iammanbeard** [comment]
Or you just skip the wrapper and use [Rekordbox Song Exporter](https://github.com/Unreal-Dan/Rekordbox Song Exporter), which is what unbox is using anyway, and is confirmed to work on 6.6.2 (at least with two decks) just fine.

**Comment by erikrichardlarson** [comment]
@djrexy You should be good to update and continue using unbox, as @iammanbeard mentioned we use @unreal-dan's [hook](https://github.com/Unreal-Dan/RekordBoxSongExporter), I talked to him a while ago and he mentioned that his exporter can now handle rekordbox updates. This way we don't need to rebuild unbox on each rb version bump, and you can continue using the overlays / Twitch extension to display tracks.

**Comment by djrexy** [comment]
@erikrichardlarson When i use exporter not looks nice, after using unbox everything looks nice. Look on sample (sample 1 exporter,sample 2 unbox
![1](https://user-images.githubusercontent.com/84639559/161445879-94bee7bf-6fc7-4e2c-b8eb-d5eefd3fc9c4.PNG)
![2](https://user-images.githubusercontent.com/84639559/161445881-c84d30f4-091b-46c2-af01-45108e9f968b.PNG)
)

**Comment by djrexy** [comment]
Rekordbox 6.6.3 is out.

**Comment by erikrichardlarson** [comment]
6.6.3 should work with the current unbox release since the underlying function [hook](https://github.com/Unreal-Dan/RekordBoxSongExporter) / launcher can handle future rekordbox updates now.

**Comment by djrexy** [comment]
so i have to copy this files to unbox folder and replace?

**Comment by erikrichardlarson** [comment]
No you shouldn't need to do anything with unbox, you can just update rekordbox and unbox should work as expected. Just let me know if you run into any issues.

**Comment by djrexy** [comment]
thank u Boss!

**Comment by djrexy** [comment]
I downloaded  song exporter 3.42 as you said and overwrited files in unbox folder, changed just patch file to rekordbox 6.6.3 and workin like charm. Thank U bro for help and hard work!
![Przechwytywanie](https://user-images.githubusercontent.com/84639559/162583610-3e1fb282-3e1c-414c-af20-b82fd5d8583c.PNG)

**Comment by djrexy** [comment]
unfortunetly this trick not working with ver.6.6.4 :(

**Comment by djrexy** [comment]
any news about working version on 6.6.4?

**Comment by erikrichardlarson** [comment]
Still waiting for an update to the underlying rb hook, once I have the update I'll be updating unbox ASAP.

**Comment by djrexy** [comment]
thanks for quick response Bro.

**Comment by gamesdepot** [comment]
Thank you for sharing this application with us. Any progress on recordbox 6.6.4?

**Comment by erikrichardlarson** [comment]
@djrexy @gamesdepot Yeah the latest release supports 6.6.4, you can download it here: https://github.com/erikrichardlarson/unbox/releases/download/10.1/unbox_windows.zip

**Comment by erikrichardlarson** [comment]
Btw there's a [discord](https://discord.gg/G28qc3SbUx) now if y'all want to join for support / to provide any feedback.

**Comment by gamesdepot** [comment]
> Btw there's a [discord](https://discord.gg/G28qc3SbUx) now if y'all want to join for support / to provide any feedback.

Thank you for your interest. discord link not working

**Comment by erikrichardlarson** [comment]
Oh weird, want to try this one: https://discord.gg/r6fJeudm
