### ISSUE TITLE
The name of the track changes during the pre-listening

### ISSUE THREAD

**Issue by Paipy74** [erikrichardlarson/unbox#40]
Hi everyone,
I use Serato and Win 10 with a Denon MCX8000.
Everything works regularly, but when I start the track that has to enter (in pre-listening), the caption changes, but in reality I'm just listening to it in the headphones.
How can I do?

**Comment by Paipy74** [comment]
Ah ok ... it's a shame.
However, I noticed that the delay to be set when launching UNBOX doesn't work well.
I have set 60 seconds of delay, but after a few seconds of loading the track into the console, the caption changes (even without going to preview or pressing Play).
Is there a solution to this?

**Comment by erikrichardlarson** [comment]
Ah there must be a bug with the Serato delay, I’ll look into this for the next release. I mentioned this in the Denon forums, but in your case you should be able to use Denon mode. I added some more details on the forum, feel free to reach out over there if you have any questions.

**Comment by erikrichardlarson** [comment]
Latest release includes Serato Live mode which will follow master, closing this for now
