### ISSUE TITLE
Unbox not reading Serato history

### ISSUE THREAD

**Issue by Djsideshow13666** [erikrichardlarson/unbox#41]
I got it to bypass the java error code by moving app to my desktop.
But now it says my last logged track is something I havent even loaded onto my serato in years.
how do i correct this? I wont change no matter which track i load.
I am using serato dj pro is that the reason?

**Comment by erikrichardlarson** [comment]
There could be an old history file that it's picking up? Serato DJ Pro should work just fine. You can remove the current History folder within the "_Serato_" folder on your machine. That should cause Serato to build a new History folder / db file for you and unbox will parse the new folder / db.

**Comment by erikrichardlarson** [comment]
@Djsideshow13666 There is a new Serato Live mode that uses the Serato Live Playlists feature that could solve your problem here

**Comment by erikrichardlarson** [comment]
Closing this for now
