### ISSUE TITLE
Why is the twitch login required? 

### ISSUE THREAD

**Issue by lord-carlos** [erikrichardlarson/unbox#45]
Hi

Why was the twitch authentication added?
Why is it required? No opt out.

With kind regards.

**Comment by erikrichardlarson** [comment]
It was added to integrate with an upcoming Twitch panel extension that will display your recent tracks. I’m actually migrating over to Userbase in place of Auth0 / Twitch, which uses a email / password login. Are you interested in opting out of logging in?

**Comment by lord-carlos** [comment]
> Are you interested in opting out of logging in?

Yes. I just downloaded an older version again.
I did not know what the login was for.

All I want is the html page. I would like if I only have to login, if it's necessary.

**Comment by erikrichardlarson** [comment]
Gotcha, I'll be sure you can access the standard features without a login in the next release.
