### ISSUE TITLE
Unable to open Database file with Mixxx 2.3.0

### ISSUE THREAD

**Issue by thanks1music** [erikrichardlarson/unbox#47]
Hey there, 

It was working great with Mixxx for a while, but I just updated and I'm getting this error saying it can't open the database file: 
<img width="424" alt="Screen Shot 2021-07-01 at 7 26 23 PM" src="https://user-images.githubusercontent.com/84488652/124200109-85d7c680-daa2-11eb-90ed-28afe863b9c6.png">

When I installed the new version of Mixxx, I had to enable some sort of access in system preferences because of "sandboxing" in the newer versions of OSX? I'm wondering if that might be the culprit.

**Comment by erikrichardlarson** [comment]
Hmmm do you have a sqlite file in the /Users/<your_name>/Library/Application Support/Mixxx/ directory?

**Comment by thanks1music** [comment]
Sorry, I didn't follow up on this. 

I finally updated Mixxx to the latest version successfully, and now the sqlite file is located here: /Users/<user>/Library/Containers/org.mixxx.mixxx/Data/Library/Application\ Support/Mixxx/mixxxdb.sqlite. The move to /Library/Containers/ seemed like it was a necessity with the update to Mixxx 2.3.0

I don't get the error message any more, but Unbox isn't pulling any of the track data. Is there any way to manually update where Unbox is looking for that .sqlite file? 

Thanks!
