### ISSUE TITLE
Twitch Login?

### ISSUE THREAD

**Issue by AdvanceRatio** [erikrichardlarson/unbox#48]
I just tried to pull the latest release, and notice it now requires a twitch login.  I don't see anything detailing why this is necessary?

Seems odd for this kind of software to require a third-party login.  Can anybody explain why this is a thing?

**Comment by erikrichardlarson** [comment]
Yeah sorry kinda confusing, but this was implemented for an upcoming Twitch panel extension that I’ll release in a few days. The extension is a tracklist that updates in real-time and persists your 20 most recent tracks, here’s an example:


https://user-images.githubusercontent.com/17460309/124286320-ac7a1980-db03-11eb-893e-dcced286a04f.mov



There will be a new release of Unbox as well when the extension is released and I’ve made the login optional in this next release so you’ll only need to login if you want the Twitch panel extension. 

Apologies for the confusion here!

**Comment by AdvanceRatio** [comment]
Gotcha!  Thanks for the clarification.
