### ISSUE TITLE
Where i can get Unbox Pro token 

### ISSUE THREAD

**Issue by djrexy** [erikrichardlarson/unbox#49]
Where i can get Unbox Pro token ? I see extension is installed on my twitch channel but in config i must paste Unbox Pro token.

**Comment by erikrichardlarson** [comment]
In the latest [release](https://github.com/erikrichardlarson/unbox/releases/download/9.0/unbox_windows.zip) you can subscribe to Unbox Pro, the token will display in the Unbox desktop app on step four after you subscribe. 
<img width="600" alt="Screen Shot 2021-07-06 at 5 06 46 PM" src="https://user-images.githubusercontent.com/17460309/124681046-8db9b100-de7c-11eb-8c17-c6cee16da9f9.png">
