### ISSUE TITLE
Unable to run on 2015 MacBook Pro with MacOS Monterey

### ISSUE THREAD

**Issue by trmazi** [erikrichardlarson/unbox#51]
Hi there! Trying to run this on my late 2015 MBP and it's not letting me start the app. Running the latest Monterey Dev beta. From what it looks like, is this possibly compiled just for M1 Macs? I'd love to get this working, it look very promising and awesome. 
<img width="372" alt="Screen Shot 2021-07-29 at 11 29 24 PM" src="https://user-images.githubusercontent.com/66042448/127595775-89b4227f-4f49-4994-a430-43ed7d3dbf76.png">

**Comment by erikrichardlarson** [comment]
Yooo yeah I'm using a M1 now and my build defaulted to arm64. I'm working to update this, but for now you can use this previous release that was built to target x86 Macs: https://github.com/erikrichardlarson/unbox/releases/download/8.2/unbox-mac.zip

Let me know if you run into any issues!

**Comment by trmazi** [comment]
thanks! will do. (sorry for the late reply.)

**Comment by MortashaKinski** [comment]
I'm also having trouble, using a MacMini 2020 M1 with Monterey.
![Screenshot 2021-12-15 at 12 57 51](https://user-images.githubusercontent.com/96184580/146190849-c57b99c8-c737-467b-9945-bc2297707514.png)

**Comment by erikrichardlarson** [comment]
@MortashaKinski can you try running this `sudo xattr -r -d com.apple.quarantine /path/to/unbox.app` where `/path/to/unbox.app` is updated to the path of unbox on your machine? I think this will allow you to open the application, longer term I plan on verifying unbox, but this should work in the meantime

**Comment by MortashaKinski** [comment]
Hi Eric,

Thanks for the reply, but I think I need to understand a few steps first.
I'm a DJ, not a tech guru, so am trying to work out what to do with your
instruction!

Kind regards,
Mortasha.
