### ISSUE TITLE
Adding remix in the display

### ISSUE THREAD

**Issue by DJUcron** [erikrichardlarson/unbox#54]
This is a great app but it only display the Artist - Title, as a DJ the remix would be a great addition to it. Not sure this is possible to be done. But this is a very good app love it.

**Comment by erikrichardlarson** [comment]
Thanks! Depending on the overlay you select and mode you're on, you may be able to get the remixer as well. Which mode are you using?

**Comment by DJUcron** [comment]
Have tried horizontal and vertical mod ans same thing. You get the Artist and the title but not the remix. But i saw you made a change so ill try it again to see

**Comment by erikrichardlarson** [comment]
Gotcha, what gear / mode are you using?

**Comment by DJUcron** [comment]
Still the same thing, for some reason it will show the artist, the title but not the remix. i play a bit with it and manage to have it show the remix but as soon as i restart the app it was not there anymore. (i'm not a programmer but i can do some stuff) And by the way the update made it way much faster to see the track playing.

As for the gear i use Rekordbox so the app is on a computer build only for the software (lenovo deskto running windows 7 64. Controller pioneer DJ400, Traktor Audio 8 and turntable with dvs. (All of this goes trough a regular mixer). And the i tried the different mod if you mean horizontal, vertical, next up and History. I tried them all. Horizontal and Vertical work like i said without remix. and as fare as next up and history not track show on that one.

The other thing i notice is there in the user folder the unbox folder and you have text file that are there. Artist,title but there is no remix text file. My other option was to use those files and set some overlay with them but since this is not there i can get the remix name out of it.

I use it with OBS as a overlay with the local server option and it work perfectly beside the remix par and that last to mod that show noting.

By the way thanks so much for this apps because of the nature of my dj setup it's impossible to go for windows 10 OS and i needed a software that would work on windows 7.

**Comment by erikrichardlarson** [comment]
Can you try using the ASOT overlay? This should display the remix in Rekordbox mode, glad you're enjoying the app!

**Comment by DJUcron** [comment]
Working perfectly in ASOT mode . Thanks for taking the time to answer.

**Comment by erikrichardlarson** [comment]
No problem, great to hear! Let me know if anything else comes up.
