### ISSUE TITLE
Now Playing.txt for Rogue Amoeba's Audio Hijack app

### ISSUE THREAD

**Issue by voxxit** [erikrichardlarson/unbox#64]
Would it be possible to get another file in this format for use with the Rogue Amoeba apps like Audio Hijack?

```
Title: Song Title
Artist: Artist Name
Album: Album Name
ArtworkData: <Base64'ed contents of image data>
Artwork: file:///Users/ammo/Desktop/artwork.png
Time: MM:SS
```

See: https://rogueamoeba.com/support/knowledgebase/?showArticle=AudioHijack-Metadata#nowplayingfile

Thanks!!

**Comment by erikrichardlarson** [comment]
Sure yeah I can look into this, what mode are you using in unbox?

**Comment by voxxit** [comment]
@erikrichardlarson Rekordbox DB
