### ISSUE TITLE
Publish Source Code

### ISSUE THREAD

**Issue by eringerli** [erikrichardlarson/unbox#69]
Please publish _all_ your source code in the repository, most of the stuff in the releases are not here.

I quote from README.md: `The source code is in this repo if you're concerned about security.` Well, it isn't.

**Comment by erikrichardlarson** [comment]
Ah sorry about that, just updated the source! Feel free to lmk if you have any other questions here.

**Comment by eringerli** [comment]
Thamks for the fast reaction, it is really appreciated. Is there source for the rekordbox_realtime stuff for windows too?

**Comment by erikrichardlarson** [comment]
No problem, yeah those files come from @Unreal-Dan's latest prebuilt [release](https://github.com/Unreal-Dan/RekordBoxSongExporter/releases/tag/3.42), he's done some incredible work [here](https://github.com/Unreal-Dan/RekordBoxSongExporter) to hook rekordbox functions on Windows. The hooks allow for loaded tracks to be cached, and reported when the master deck switches.
