### ISSUE TITLE
MacOS OBS browser plugin CSS workaround

### ISSUE THREAD

**Issue by oh6fub** [erikrichardlarson/unbox#7]
It seems that MacOS version of OBS has little trouble in rendering the CSS correctly. There is very little information about this, but following forum post hinted to right direction: https://obsproject.com/forum/threads/css-of-browser-source-rendering-wrong.133496/

For example, I get the coloured header boxes rendered incorrectly (not completely filled, "Now Playing" divided on two lines). Since unbox uses bootstrap and is up-to-date but OBS browser not, the workaround is to inject custom CSS such as:

```
.col-3 {
    max-width: 40%;
}
```

<img width="333" alt="unbox-obs" src="https://user-images.githubusercontent.com/9314211/104806599-6f35ff80-57e1-11eb-9aba-6e6fc97e3185.png">
<img width="564" alt="unboxfix" src="https://user-images.githubusercontent.com/9314211/104806600-70672c80-57e1-11eb-9605-4aacd289c23f.png">

**Comment by erikrichardlarson** [comment]
@oh6fub Thanks for this! 

The overlays were designed according to the average browser window size (1366px x 784px), so you can also set the Width and Height properties on the browser source properties page according to this size and you should end up with something like this:
<img width="794" alt="Screen Shot 2021-01-16 at 10 04 05 AM" src="https://user-images.githubusercontent.com/17460309/104819414-2cc0f280-57e2-11eb-93f3-bbc320a45728.png">

**Comment by djmel88** [comment]
How can I make the text wide and not crunched up? What command can input?

**Comment by oh6fub** [comment]
You are correct, increasing the browser window size does the trick too. Maybe I was thinking this over complicated :) If the size of window bothers, it can always be cropped (of course it is transparent anyway)

Best app so far!
