### ISSUE TITLE
Right Align Text and Header

### ISSUE THREAD

**Issue by mrmacau** [erikrichardlarson/unbox#70]
It's not so much an issue as it works perfectly for me using VDJ but I couldn't find anywhere else to ask this.

I am trying to right align everything that is displayed.  I use the ASOT overlay and I used your example CSS to add the shadow but I can't work out how to right align everything.  I am not all that familiar with CSS.

I managed to get the track title and artist to right align as opposed to left but I can't figure out how to right align the "now playing" box and text.

Appreciate any help.

**Comment by erikrichardlarson** [comment]
Hey sorry for the delay here, I'll send out some CSS this week to get your overlay right aligned!

**Comment by mrmacau** [comment]
Thanks mate.  Like I said.  Not an issue as it works perfectly!

Appreciate your help and no rush.  Whenever you have the free time.

Cheers.

**Comment by mrmacau** [comment]
> Hey sorry for the delay here, I'll send out some CSS this week to get your overlay right aligned!

Any chance of getting that CSS?

**Comment by erikrichardlarson** [comment]
Yeah so sorry about the delay, will send this over this week!

**Comment by mrmacau** [comment]
> Yeah so sorry about the delay, will send this over this week!

Thank you!!

**Comment by erikrichardlarson** [comment]
Hey ended up just creating a new overlay called `asot_right` you can unzip this and drop the html file into the overlays directory in the unbox app directory, are you on Mac or Windows?
[asot_right.html.zip](https://github.com/erikrichardlarson/unbox/files/8106681/asot_right.html.zip)

**Comment by mrmacau** [comment]
> Hey ended up just creating a new overlay called `asot_right` you can unzip this and drop the html file into the overlays directory in the unbox app directory, are you on Mac or Windows? [asot_right.html.zip](https://github.com/erikrichardlarson/unbox/files/8106681/asot_right.html.zip)

Windows here.

**Comment by erikrichardlarson** [comment]
Nice if you go to the `resources\app\overlays` directory in the unbox app directory you should be able to copy the `asot_right` file there, and you can load the overlay with `http://localhost:8080/asot_right.html`

**Comment by mrmacau** [comment]
> Nice if you go to the `resources\app\overlays` directory in the unbox app directory you should be able to copy the `asot_right` file there, and you can load the overlay with `http://localhost:8080/asot_right.html`

Just tested and works perfectly!  Thank you.  Appreciate your time and effort!
