### ISSUE TITLE
Subscribed but password rejected and I can't update it

### ISSUE THREAD

**Issue by BobDM** [erikrichardlarson/unbox#74]
All in the title, I just subscribed but can't log in due to the password not being recognised (despite being set moments prior) and I can't see any way to reset it.

**Comment by erikrichardlarson** [comment]
Hey sorry about this, can you send me an email: erikrichardlarson@gmail.com, I can send over a password reset email ASAP

**Comment by BobDM** [comment]
Appreciated. Just mailed you.

**Comment by BobDM** [comment]
I haven't received anything yet, please reopen?
