### ISSUE TITLE
Need a password reset option sent. The previous issue was closed but I haven't received anything, sorry.

### ISSUE THREAD

**Issue by BobDM** [erikrichardlarson/unbox#75]
Hey sorry about this, can you send me an email: erikrichardlarson@gmail.com, I can send over a password reset email ASAP

_Originally posted by @erikrichardlarson in https://github.com/erikrichardlarson/unbox/issues/74#issuecomment-1046164225_

**Comment by erikrichardlarson** [comment]
Oh sorry about that, it seems like you signed up with a gmail domain, but your email may actually be at a hotmail domain?

**Comment by BobDM** [comment]
Wow. Entirely my fault, please close and we'll talk on mail.
