### ISSUE TITLE
Can't install on Mac OS Monterey (Macbook Pro Mid 2015)

### ISSUE THREAD

**Issue by Nass86** [erikrichardlarson/unbox#79]
I've tried to install this but it's having none of it... there's a graphic overlayed onto yours as if to say it can't even attempt to install it (it isn't compatible with Monterey).

![Screenshot 2022-03-29 at 23 13 07](https://user-images.githubusercontent.com/80380533/160698834-a05bb515-4836-4962-b694-549ba5d786f5.jpg)

**Comment by erikrichardlarson** [comment]
Can you try installing this version? https://github.com/erikrichardlarson/unbox/releases/download/10.0/unbox_mac_intel.zip
