### ISSUE TITLE
Lag time on Now Playing

### ISSUE THREAD

**Issue by DJNixInTheMix** [erikrichardlarson/unbox#8]
It seems to take at least 1 minute for the Now Playing track to update.  Any way to reduce the latency?
BTW This works absolutely great otherwise... fabulous.  
Thanks,
Nick

**Comment by erikrichardlarson** [comment]
Not at the moment, this is a rekordbox limitation. I'm looking for ways around this, but I'm not sure if I'll be able to find a way. 

Good to hear!

**Comment by DJNixInTheMix** [comment]
Thanks for the quick reply.  Rekordbox does seem to get it over to KUVO Live Playlist quicker if that helps... but I'm having issues with the way they sort the playlist.  Thanks much again. -Nick

**Comment by erikrichardlarson** [comment]
Ohh good to know. I was actually just looking at the KUVO live playlists tonight, and I think I'm going to create a "Rekordbox KUVO" mode that will parse the web page that the live playlist is rendered on. This would give rekordbox 5 users access, and it sounds like it could solve the lag here. I'll post what I can find here, you can probably expect to see this feature in the next release this week or next.

**Comment by DJNixInTheMix** [comment]
Here's the issue I'm having with KUVO Live playlist.  It starts out sorted with the most recent track on top which is cool because when I use a cropped browser source in OBS, the current track is in the same position on the webpage.  However, for no reason ant any point during the session, the order reverses which now shows the first track I played in my source.  I sent an e-mail to KUVO Pioneer support which they responded with "We are afraid that the order can not be customized. 
We've forwarded your feedback to our product development team".  Then I was digging into https://kuvo.com/support/ and if you scroll down to March 20. 2019 you'll see they addressed it .... but didn't.

We’ve updated KUVO website and KUVO app (iOS, Android).
KUVO Website
KUVO app (iOS) Ver 3.1.4
KUVO app (Android) Ver 3.1.8

– Viewing archive event information becomes available in the club’s and user’s profile page.
– Listing the most recent tracks at the top of the live playlist sent from KUVO clubs and rekordbox.

I hope this helps somewhat and it's as far as I've gotten. Once again thanks MUCH.
-Nick

**Comment by erikrichardlarson** [comment]
Oh weird, I'll handle any odd sorting issues when I parse the page. I just tested out KUVO, and it definitely logs in real-time, expect more real-time logging this week with the next release. Thanks for sending over this info!

**Comment by fivefortyfour** [comment]
I second the lag issue. Kuvo does show the tracks a bit quicker but relies on an internet connection at all times.
Just testing unbox today... what's the trigger to refresh the browser window? Does unbox force the refresh?  Does webpage caching effect what's in the local webpage too?

**Comment by DJNixInTheMix** [comment]
@erikrichardlarson I was wondering if you could also pull the Record Label and Year fields as well.  Not essential but a 'nice to have'
Thanks again

**Comment by erikrichardlarson** [comment]
@DJNixInTheMix Just released the update that allows you to use KUVO live playlists. I'll be sure to add in a year / label overlay on the next release. The "ASOT" release has label and you can use that now.

**Comment by erikrichardlarson** [comment]
@fivefortyfour The window doesn't refresh actually, there is some JS that runs on an interval grabbing new data as it is stored locally. This gets around any caching issues that you might run into with a page that doesn't make ajax calls.
