### ISSUE TITLE
No Connection To Denon SC6000 with Denon Mixer 1850

### ISSUE THREAD

**Issue by Farbstoff** [erikrichardlarson/unbox#86]
Hey,

i try to use your great tool, but i cant connect to my Denon Equipment. Network is rdy. I can Ping the mixer from my PC.

Unbox StagelinQ Log: 2022/06/01 18:26:41 Listening for devices for 5s
Unbox StagelinQ Log: 2022/06/01 18:26:46 Added this device: 127.0.0.1 "OBS_Plug" "Icedream StagelinQ Receiver" "0.0.0"

That is all what happened

**Comment by Farbstoff** [comment]
Hey thx for the fast response.

I use the latest version 9,2. The Denon SC6000 use the version 2.2 and mixer v1.5.
And i use the Windows Version

**Comment by erikrichardlarson** [comment]
Gotcha seems like the poller didn't actually start in 9.2, can you go into the folder`unbox_windows\resources\app\denon` and run `unbox_denon_poller.exe`, this should start the poller that will connect to your device and start reporting your tracks.

**Comment by Farbstoff** [comment]
I tried that , Yesterday and tofay again .. nothing He listen for 5 sec and then nothing

**Comment by erikrichardlarson** [comment]
Gotcha what is the Mixer PC port connected to?

**Comment by Farbstoff** [comment]
The USB PC connection is directly connected to the PC running your software.

**Comment by erikrichardlarson** [comment]
![image](https://user-images.githubusercontent.com/17460309/171900493-8f2213e6-046c-441e-aa02-a94953aed7e6.png)

Is the PC Lan Hub port (far right above) plugged in your home network switch?

**Comment by Farbstoff** [comment]
yes

the Pc port is linked with the router , and port 1 - 4 to the player.

**Comment by erikrichardlarson** [comment]
Hmm can you try running this version: https://github.com/erikrichardlarson/unbox/releases/download/9.0/unbox_windows.zip

If that doesn't work then I can refund your premium sub, and send you an update when I'm able to test Denon mode updates on some Denon gear again.

**Comment by erikrichardlarson** [comment]
Also can you turn on your Denon mixer at the same time you turn on Unbox? This can help with initial discovery of the device. Just let me know if you're still running into issues, will refund your premium sub if we can't figure this out.

**Comment by Farbstoff** [comment]
Today, i will Test all Your ideas.

**Comment by Farbstoff** [comment]
No please no refund. Work must be rewarded :)

So today i had time to test some parts of changes. And it works.
The big problem was Avast with the firewall settings in windows. i must delete avast, deactivate the windows firewall. 
Reinstall Avast and Firewall On. After the restart of unbox it found the equipment :)

`Unbox StagelinQ Log: 2022/06/05 16:26:12 Listening for devices for 5s
Unbox StagelinQ Log: 2022/06/05 16:26:14 Added this device: 192.168.178.27 "sc6000" "JP13" "2.2.0"
Unbox StagelinQ Log: 2022/06/05 16:26:14 Added this device: 192.168.178.27 "sc6000" "OfflineAnalyzer" "1.0.0"
Unbox StagelinQ Log: 2022/06/05 16:26:14 Added this device: 192.168.178.27 "sc6000" "OfflineAnalyzer" "1.0.0"
Unbox StagelinQ Log: 2022/06/05 16:26:14 Added this device: 192.168.178.26 "DN-X1800Prime" "JM08" "1.00"
Unbox StagelinQ Log: 2022/06/05 16:26:15 Added this device: 192.168.178.28 "sc6000" "JP13" "2.2.0"
Unbox StagelinQ Log: 2022/06/05 16:26:15 Added this device: 192.168.178.28 "sc6000" "OfflineAnalyzer" "1.0.0"
Unbox StagelinQ Log: 2022/06/05 16:26:15 Added this device: 192.168.178.28 "sc6000" "OfflineAnalyzer" "1.0.0"
Unbox StagelinQ Log: 2022/06/05 16:26:17 192.168.178.27 "Found StageLinQ Device on Network"
Unbox StagelinQ Log: 2022/06/05 16:26:17 192.168.178.27 "Found StageLinQ Device on Network"
Unbox StagelinQ Log: 2022/06/05 16:26:17 192.168.178.27 "Found StageLinQ Device on Network"
Unbox StagelinQ Log: 2022/06/05 16:26:17 	attempting to connect to this device…
Unbox StagelinQ Log: 2022/06/05 16:26:17 192.168.178.28 "Found StageLinQ Device on Network"
Unbox StagelinQ Log: 2022/06/05 16:26:17 192.168.178.28 "Found StageLinQ Device on Network"
Unbox StagelinQ Log: 2022/06/05 16:26:17 	attempting to connect to this device…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	attempting to connect to this device…
Unbox StagelinQ Log: 2022/06/05 16:26:17 192.168.178.28 "Found StageLinQ Device on Network"
Unbox StagelinQ Log: 2022/06/05 16:26:17 	attempting to connect to this device…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	attempting to connect to this device…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	attempting to connect to this device…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	requesting device data services…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	requesting device data services…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	requesting device data services…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	requesting device data services…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	requesting device data services…
Unbox StagelinQ Log: 2022/06/05 16:26:17 	requesting device data services…
Unbox StagelinQ Log: 2022/06/05 16:26:18 	offers FileTransfer at port 34107
Unbox StagelinQ Log: 2022/06/05 16:26:18 	offers FileTransfer at port 46459
Unbox StagelinQ Log: 2022/06/05 16:26:18 	offers FileTransfer at port 32853
Unbox StagelinQ Log: 2022/06/05 16:26:18 	offers FileTransfer at port 36109
Unbox StagelinQ Log: 2022/06/05 16:26:18 	offers StateMap at port 41439
Unbox StagelinQ Log: 2022/06/05 16:26:18 	offers StateMap at port 41361
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Librarian/DevicesController/CurrentDevice 
 State value: map[string: type:8]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Librarian/DevicesController/HasSDCardConnected 
 State value: map[state:false type:1]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Librarian/DevicesController/HasUsbDeviceConnected 
 State value: map[state:true type:1]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/LayerB 
 State value: map[state:true type:1]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Player 
 State value: map[string:1 type:4]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor1 
 State value: map[color:#ff2b84ef type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor1A 
 State value: map[color:#ffbc3cc3 type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor1B 
 State value: map[color:#fff9ce19 type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor2 
 State value: map[color:#ff2b84ef type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor2A 
 State value: map[color:#ffbc3cc3 type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor2B 
 State value: map[color:#fff9ce19 type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor3A 
 State value: map[color:#fff9ce19 type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor3B 
 State value: map[color:#ffbc3cc3 type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor4A 
 State value: map[color:#fff9ce19 type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/PlayerColor4B 
 State value: map[color:#ffbc3cc3 type:16]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Client/Preferences/Profile/Application/SyncMode 
 State value: map[string:Beat type:4]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/CurrentBPM 
 State value: map[type:0 value:120]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/ExternalMixerVolume 
 State value: map[type:0 value:0]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/ExternalScratchWheelTouch 
 State value: map[state:false type:2]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/Pads/View 
 State value: map[string:CUES type:4]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/Play 
 State value: map[state:false type:1]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/PlayState 
 State value: map[state:false type:1]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/Speed 
 State value: map[type:0 value:0.5]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/SpeedNeutral 
 State value: map[state:true type:1]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/SpeedOffsetDown 
 State value: map[state:false type:1]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/SpeedOffsetUp 
 State value: map[state:false type:1]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/SpeedRange 
 State value: map[string:8 type:4]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/SpeedState 
 State value: map[type:0 value:0]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/SyncMode 
 State value: map[string:Off type:4]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/Track/ArtistName 
 State value: map[string: type:8]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/Track/Bleep 
 State value: map[state:false type:2]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/Track/CuePosition 
 State value: map[type:14 value:0]
Unbox StagelinQ Log: 2022/06/05 16:26:18 State logged: /Engine/Deck1/Track/CurrentBPM 
 State value: map[type:0 value:120]`
