### ISSUE TITLE
windows 10 rb 5.85  A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by capellavacancies** [erikrichardlarson/unbox#9]
![immagine](https://user-images.githubusercontent.com/58681964/105568767-38f60400-5d3c-11eb-82a0-feb0a963bcce.png)
I've got to specify that my rb library is synced between two computers using dropbox. I followed this tutorial
https://forums.pioneerdj.com/hc/en-us/articles/115005245643

**Comment by erikrichardlarson** [comment]
This usually means you don't have rekordbox 6 installed. I can make a rekordbox 5 only mode for the next release, but for now you can just download rekordbox 6 and install it, no need to use it or actually upgrade, this install just needs to exist and the current release will work. Does that make sense?

**Comment by capellavacancies** [comment]
I installed rb6, same issue
so I ran it without converting my rb, same issue

plus I saw I don't have any rekordboxagent folder

**Comment by erikrichardlarson** [comment]
Interesting, did you open rb6? It may be that the folder isn't generated until rb6 is open or at least one track is imported into rb6.

**Comment by erikrichardlarson** [comment]
this should be fixed with the latest release, let me know if you continue to see issues
