### ISSUE TITLE
Rekordbox 6.6.4 write realtime .txt file pls

### ISSUE THREAD

**Issue by tuvok81** [erikrichardlarson/unbox#91]
Gives a entry or a change, where i can create or update the *.txt files faster? 
When i play a Song it push the txt file in 1min 20sec .. it was nice when you can tell us where we can make this faster all 5-10sec
or in Real Time..

thx

**Comment by erikrichardlarson** [comment]
Are you on Windows or Mac?

**Comment by tuvok81** [comment]
Windows

**Comment by erikrichardlarson** [comment]
Nice, can you try the latest version with the Rekordbox real-time mode? https://github.com/erikrichardlarson/unbox/releases/download/10.1/unbox_windows.zip

**Comment by tuvok81** [comment]
yes i will check it

**Comment by tuvok81** [comment]
its the same Problem @erikrichardlarson

**Comment by tuvok81** [comment]
@erikrichardlarson have you any ideas?

**Comment by erikrichardlarson** [comment]
What is the current delay you're seeing? Just curious if you use the non real-time rekordbox mode what kind of latency do you see?

**Comment by tuvok81** [comment]
1:20min

**Comment by erikrichardlarson** [comment]
Does your "master" indicator in rekordbox change as expected? Wondering if rb itself isn't switching the master deck when you'd expect?

**Comment by tuvok81** [comment]
oh sorry can we check that with the new version? sorry i have longer no time
