### ISSUE TITLE
What use is the MIT license when there is no source code for the binaries?

### ISSUE THREAD

**Issue by FunctionDJ** [erikrichardlarson/unbox#93]

**Comment by erikrichardlarson** [comment]
The MIT license applies to the source code that builds the binaries which are included here in the mac and windows directories, the binaries can be built directly with electron-packager on Windows or electron-builder on Mac.

**Comment by FunctionDJ** [comment]
@erikrichardlarson oh i thought there was something like a closed-source binary and some external web stuff. my bad, i misunderstood. i didn't know those binaries are built using electron.
